app/assets/javascripts/application.js
app/assets/javascripts/users/index.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/users.scss
app/views/users/index.html.haml
db/migrate/20190715034654_devise_create_users.rb
db/schema.rb

Copy confirm link

---

.gitignore
Gemfile
Gemfile.lock
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/confirmation_instructions.html.haml
app/workers/user_worker.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb
config/sidekiq.yml
docker-compose.yml
docker-env-example

add smtp with mandrill

---

config/routes.rb

production: allow only system admin access sidekiq web

---

app/assets/javascripts/programs/settings.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/settings.scss
app/controllers/application_controller.rb
app/controllers/programs/settings_controller.rb
app/models/program.rb
app/views/programs/settings/show.html.haml
config/application.rb
config/locales/format/en.yml
config/locales/program/en.yml
config/locales/sidebar/km.yml
db/migrate/20191104023615_add_column_language_code_to_programs.rb
db/schema.rb

add switch language

---

app/views/events/fields/_mapping.html.haml
lib/samples/milestone.rb

fix mapping field

---

app/models/concerns/events/searchable.rb
app/models/field.rb
app/models/program.rb
db/migrate/20190719021436_create_fields.rb
db/schema.rb
lib/samples/elasticsearch.rb
spec/factories/fields.rb
spec/models/field_spec.rb

es: update event schema

---

app/assets/javascripts/application.js
app/assets/javascripts/milestones/index.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/milestones.scss
app/controllers/milestones_controller.rb
app/models/milestone.rb
app/views/milestones/_predefined_fields.html.haml
app/views/milestones/index.html.haml
config/routes.rb
spec/models/milestone_spec.rb

Drag drop milestone

---

app/assets/javascripts/milestones/new.coffee
app/assets/stylesheets/milestones.scss
app/assets/stylesheets/shared/field_fields.scss
app/models/field.rb
app/views/milestones/_field_fields.html.haml
db/migrate/20191105043421_add_column_color_required_to_fields.rb
db/schema.rb
lib/samples/milestone.rb

milestone: fix handling mapping field

---

app/models/concerns/events/searchable.rb

elasticsearch: fix event schema

---

app/assets/javascripts/events/show.coffee
app/assets/stylesheets/events.scss
app/models/event.rb
app/models/event_milestone.rb
app/models/field.rb
app/views/events/index.html.haml
app/views/events/show.html.haml
config/locales/event/en.yml
spec/models/event_spec.rb

event: set uuid to 8 digit

---

app/assets/javascripts/application.js
app/assets/javascripts/application/util.coffee
app/assets/javascripts/event_milestones/new.coffee
app/assets/javascripts/events/index.coffee
app/assets/javascripts/telegrams/new.coffee
app/assets/stylesheets/events.scss
app/assets/stylesheets/shared/common.scss
app/controllers/events_controller.rb
app/helpers/events_helper.rb
app/models/event.rb
app/views/events/_events.html.haml
app/views/events/_filter.html.haml
app/views/events/fields/_date.html.haml
app/views/events/fields/_integer.html.haml
app/views/events/index.html.haml
app/views/events/index.js.erb
config/locales/event/en.yml

Event filter

---

app/controllers/api/v1/event_milestones_controller.rb
app/controllers/api/v1/events_controller.rb
app/controllers/api/v1/milestone/fields_controller.rb
app/controllers/api/v1/milestones_controller.rb
app/models/event.rb
app/models/event_milestone.rb
app/models/field_option.rb
app/models/field_value.rb
app/models/milestone.rb
app/serializers/event_milestone_serializer.rb
app/serializers/field_serializer.rb
config/routes.rb
spec/models/event_milestone_spec.rb
spec/models/message_interpretor_spec.rb

add api for supporting hub connecotr

---

app.env.example
app/assets/stylesheets/events.scss
app/controllers/api/v1/milestone/fields_controller.rb
app/controllers/downloads_controller.rb
app/controllers/events_controller.rb
app/models/field_value.rb
app/models/milestone.rb
app/services/event_service.rb
app/views/events/_event_info.html.haml
app/views/events/_filter.html.haml
config/locales/event/en.yml
config/routes.rb

add download csv

---

app/models/concerns/events/field_value_validation.rb
app/models/field.rb
app/models/field_values/date_field.rb
app/models/field_values/integer_field.rb
app/models/fields/date_field.rb
app/models/fields/date_time_field.rb
app/models/fields/file_field.rb
app/models/fields/image_field.rb
app/models/fields/integer_field.rb
app/models/fields/location_field.rb
app/models/fields/mapping_field.rb
app/models/fields/note_field.rb
app/models/fields/select_multiple_field.rb
app/models/fields/select_one_field.rb
app/models/fields/text_field.rb
spec/factories/field_values.rb
spec/models/field_values/date_field_spec.rb
spec/models/field_values/integer_field_spec.rb

fix field value validation for date field

---

app/models/event_type.rb
app/views/event_types/index.html.haml
db/migrate/20191227095301_add_code_to_event_types.rb
db/schema.rb
spec/models/event_type_spec.rb

add code to event type

---

app/assets/stylesheets/events.scss
app/uploaders/file_uploader.rb
app/uploaders/image_uploader.rb
app/views/events/_event_info.html.haml

fix file path and image path

---

app/models/milestone.rb
lib/samples/elasticsearch.rb
lib/samples/event.rb
lib/samples/event_type.rb
lib/samples/location.rb
lib/samples/milestone.rb

Simulation

---

app/assets/javascripts/event_milestones/new.coffee
app/assets/javascripts/milestones/new.coffee
app/assets/stylesheets/events.scss
app/controllers/events_controller.rb
app/models/concerns/events/field_value_validation.rb
app/models/field_values/date_time_field.rb
app/models/field_values/location_field.rb
app/models/field_values/note_field.rb
app/models/field_values/select_multiple_field.rb
app/views/events/_event_info.html.haml
app/views/events/_field_value_fields.html.haml
app/views/events/_form.html.haml
app/views/events/fields/_commune_id.html.haml
app/views/events/fields/_date.html.haml
app/views/events/fields/_date_time.html.haml
app/views/events/fields/_district_id.html.haml
app/views/events/fields/_file.html.haml
app/views/events/fields/_image.html.haml
app/views/events/fields/_integer.html.haml
app/views/events/fields/_label_name.html.haml
app/views/events/fields/_location.html.haml
app/views/events/fields/_note.html.haml
app/views/events/fields/_province_id.html.haml
app/views/events/fields/_select_multiple.html.haml
app/views/events/fields/_select_one.html.haml
app/views/events/fields/_text.html.haml
app/views/events/fields/_village_id.html.haml
app/views/milestones/_field_fields.html.haml
app/views/milestones/_predefined_fields.html.haml

Enhance milestone fild ui

---

Dockerfile
docker-compose.prod.yml
docker-compose.yml

- Fixed Dockerfile assets:precompile to use RAILS_MASTER_KEY(Rails 5.2)
- Remove unused Kibana docker image in compose
- Adding docker-compose.prod.yml for production mode

Docker compose production

---

app/assets/javascripts/events/index.coffee
app/models/concerns/events/field_value_validation.rb
app/serializers/field_value_serializer.rb
app/views/client_apps/_guideline_event.html.haml
app/views/client_apps/_guideline_events.html.haml
app/views/client_apps/_guideline_milestones.html.haml
app/views/client_apps/_guideline_post_event.html.haml
app/views/client_apps/_guideline_post_event_milestone.html.haml
app/views/client_apps/_guideline_put_event.html.haml
app/views/client_apps/_guideline_put_event_milestone.html.haml
app/views/client_apps/info.html.haml
config/locales/client_app/en.yml
config/locales/shared/en.yml

Api guideline

---

app/assets/javascripts/events/new.coffee
app/assets/stylesheets/events.scss
app/controllers/events_controller.rb
app/models/event.rb
app/views/events/_event_info.html.haml
app/views/events/_form.html.haml
app/views/events/_link_event_modal.html.haml
app/views/events/_link_events.html.haml
app/views/events/_next_link.html.haml
app/views/events/fields/_date_time.html.haml
app/views/events/fields/_text.html.haml
app/views/events/search.js.erb
config/initializers/pagy.rb
config/locales/event/en.yml
config/routes.rb
db/migrate/20200120092533_add_link_uuid_to_events.rb
db/schema.rb

Link event

---

app/views/milestones/telegrams/_stepper_template_fields.html.haml

Telegram: fix display program milestone step

---

app/assets/stylesheets/shared/common.scss
app/views/events/index.html.haml
config/locales/event/en.yml
config/locales/event/km.yml

Event pagination enhancement

---

app/assets/javascripts/application.js
app/views/events/fields/_date_time.html.haml

close datetime picker when lose focus

---

app/models/field_values/date_time_field.rb
config/application.rb

elasticsearch: set timezone for datetime value

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/_filter.html.haml
app/views/users/index.html.haml
config/locales/shared/en.yml
config/locales/shared/km.yml
config/locales/user/en.yml

enhance user listing

---

app/models/field_values/date_field.rb
app/models/field_values/integer_field.rb
spec/models/field_values/date_field_spec.rb
spec/models/field_values/integer_field_spec.rb

allow blank field value for integer and date

---

app/assets/javascripts/milestones/new.coffee
app/controllers/milestones_controller.rb
app/models/field.rb
app/models/field_value.rb
app/models/field_values/mapping_field.rb
app/models/field_values/select_one_field.rb
app/views/events/fields/_mapping.html.haml
app/views/events/fields/_select_multiple.html.haml
app/views/events/fields/_select_one.html.haml
app/views/milestones/_mapping_field_content.html.haml
config/locales/milestone/en.yml
config/locales/milestone/km.yml
db/migrate/20200220040547_add_mapping_field_id_to_fields.rb
db/schema.rb
docker-compose.yml
lib/samples/db/cdc_milestone.json
lib/samples/milestone.rb
spec/factories/milestones.rb
spec/models/field_spec.rb

Event detail fix select one value

---

Gemfile.lock
app/assets/javascripts/users/new.coffee
app/controllers/locations_controller.rb
app/controllers/users_controller.rb
app/models/location.rb
app/models/user.rb
app/policies/event_policy.rb
app/policies/user_policy.rb
app/views/events/fields/_province_id.html.haml
app/views/users/_form.html.haml
app/views/users/edit.html.haml
app/views/users/index.html.haml
app/views/users/new.html.haml
config/locales/user/en.yml
config/locales/user/km.yml
config/routes.rb
db/migrate/20200221085031_add_province_code_to_users.rb
db/schema.rb
docker-compose.yml
lib/samples/user.rb
spec/factories/event_types.rb
spec/factories/events.rb
spec/factories/user.rb
spec/models/location_spec.rb
spec/models/user_spec.rb
spec/policies/event_policy_spec.rb

Assign user specific province

---

app/models/milestone.rb
app/views/events/index.html.haml
app/views/events/show.html.haml
app/views/events/show/_event_progress.html.haml
app/views/milestones/_form.html.haml
app/views/milestones/index.html.haml
db/migrate/20200221033811_add_verified_column_to_milestones.rb
db/schema.rb
spec/models/milestone_spec.rb

Enhancement: enable milestones below verification milestone

---

app/assets/stylesheets/shared/common.scss
app/models/concerns/events/searchable.rb
app/views/events/index.html.haml
app/views/events/show/_event_info.html.haml
config/locales/event/en.yml
config/locales/event/km.yml

Suspected event

---

Gemfile
Gemfile.lock
app.env.example
app/controllers/application_controller.rb
config/application.rb
config/initializers/sentry_logger.rb

integrate sentry logger

---

app/controllers/milestones_controller.rb
app/models/event.rb
app/models/field_values/mapping_field.rb
app/models/field_values/select_multiple_field.rb
app/views/events/fields/_select_multiple.html.haml
app/views/events/show.html.haml
app/views/events/show/_event_progress.html.haml

fix select multiple

---

app/models/event.rb
app/models/field_value.rb
db/migrate/20200310095140_add_event_date_to_events.rb
db/schema.rb
spec/models/field_value_spec.rb

Event: sort event listing

---

app/assets/javascripts/events/show.coffee
app/assets/javascripts/events/skip_logic.js
app/assets/javascripts/pdf.js
app/assets/stylesheets/pdf.scss
app/views/events/previews/show.pdf.haml
app/views/events/show/_event_info.html.haml

Section: handle render skip logic

---

app/models/user.rb
app/views/shared/_sidebar.html.haml
app/views/users/_form.html.haml
app/views/users/index.html.haml
config/locales/user/en.yml
config/locales/user/km.yml
db/migrate/20200326103118_add_full_name_to_users.rb
db/schema.rb
lib/tasks/user.rake
spec/models/user_spec.rb

add user full name

---

app/controllers/telegram_webhooks_controller.rb
app/models/chat_group.rb
db/migrate/20200713035713_change_column_chat_id_in_chat_groups.rb
db/schema.rb
lib/tasks/chat_group.rake

After re-added telegram bot, please run the following code
```
ChatGroup.where(chat_type: 'supergroup').each do |supergroup|
if chat_group = ChatGroup.where(title: supergroup.title, chat_type: 'group').first.presence
chat_group.update(chat_id: supergroup.chat_id, chat_type: supergroup.chat_type)
supergroup.destroy
end
end
```

fix telegram bot for super group

---

app/assets/javascripts/milestones/new.coffee
app/assets/stylesheets/pdf.scss
app/assets/stylesheets/shared/base.scss
app/assets/stylesheets/shared/field_fields.scss
app/models/field_values/select_multiple_field.rb
app/models/field_values/select_one_field.rb
app/models/notifiers/account_owner_telegram_notifier.rb
app/models/notifiers/receive_program_notification_telegram_notifier.rb

Select field: add color and display as badge

---

app/assets/javascripts/application.js
app/assets/javascripts/events/channels_form.js
app/assets/javascripts/events/follow_up.js
app/assets/javascripts/events/index.coffee
app/assets/stylesheets/follow_ups.scss
app/controllers/events/follow_ups_controller.rb
app/jobs/lock_event_job.rb
app/models/follow_up.rb
app/views/events/follow_ups/_popup.haml
app/views/events/index/_follow_up.haml
app/views/shared/buttons/_copy_button.html.haml
config/locales/event/en.yml
config/locales/event/km.yml
config/locales/shared/en.yml
config/locales/shared/km.yml
config/routes.rb
config/sidekiq.yml
db/migrate/20220902070833_add_resolved_at_to_follow_ups.rb
db/schema.rb
spec/services/mbds_outbreak_report_service_spec.rb
spec/support/vcr.rb

Event follow up: add resolved at

---

.github/workflows/rubyonrails.yml
spec/models/event_milestones/notify_event_creator_callback_spec.rb
spec/models/follow_up_spec.rb
spec/services/mbds_outbreak_report_service_spec.rb

add yaml file for running github action
